services:
  - type: web
    name: portfolio-builder
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: portfolio-builder
          property: url
      - key: PUBLIC_BASE_URL
        fromService:
          type: web
          name: portfolio-builder
          property: url
      - key: UPLOAD_DIR
        value: ./uploads
